"""
Gone in 60 Parsecs
==================
A space heist game where you hack enemy ships using cybersecurity knowledge.
Operate from Asteroid Dottie and steal the most legendary ships in the galaxy.
"""


# ─────────────────────────────────────────────
#  CYBERSECURITY QUESTION BANK
#  Format: (question, correct_answer, [choices])
# ─────────────────────────────────────────────
QUESTION_BANK = {
    "Network Security": [
        ("What does a firewall primarily do?",
         "b",
         ["a) Speeds up your internet",
          "b) Monitors and controls incoming/outgoing network traffic",
          "c) Stores passwords securely",
          "d) Encrypts your hard drive"]),
        ("What does 'DDoS' stand for?",
         "c",
         ["a) Data Driven Operating System",
          "b) Dynamic Denial of Service",
          "c) Distributed Denial of Service",
          "d) Dual Defense over Systems"]),
        ("Which protocol is used for secure web browsing?",
         "a",
         ["a) HTTPS",
          "b) FTP",
          "c) HTTP",
          "d) SMTP"]),
        ("What is a VPN used for?",
         "b",
         ["a) Speeding up downloads",
          "b) Creating an encrypted tunnel for internet traffic",
          "c) Storing files in the cloud",
          "d) Managing network hardware"]),
        ("What is port scanning used for?",
         "d",
         ["a) Checking how fast your printer is",
          "b) Measuring internet bandwidth",
          "c) Backing up data",
          "d) Discovering open ports and services on a network"]),
        ("Which layer of the OSI model does a router operate at?",
         "c",
         ["a) Layer 1 - Physical",
          "b) Layer 2 - Data Link",
          "c) Layer 3 - Network",
          "d) Layer 4 - Transport"]),
    ],
    "Encryption": [
        ("What does AES stand for?",
         "b",
         ["a) Automatic Encryption Standard",
          "b) Advanced Encryption Standard",
          "c) Applied Encryption System",
          "d) Authenticated Exchange Standard"]),
        ("In asymmetric encryption, what is the public key used for?",
         "a",
         ["a) Encrypting data",
          "b) Decrypting data",
          "c) Signing certificates",
          "d) Storing passwords"]),
        ("What is a hash function's main property?",
         "c",
         ["a) It can be reversed easily",
          "b) It always produces the same length output as input",
          "c) It produces a fixed-size output and is one-way",
          "d) It requires two keys"]),
        ("What does SSL/TLS protect?",
         "d",
         ["a) Local file storage",
          "b) RAM memory",
          "c) USB drives",
          "d) Data transmitted over a network"]),
        ("Which of these is a symmetric encryption algorithm?",
         "a",
         ["a) AES",
          "b) RSA",
          "c) ECC",
          "d) Diffie-Hellman"]),
        ("What is a digital certificate used for?",
         "b",
         ["a) Encrypting hard drives",
          "b) Verifying the identity of a website or user",
          "c) Compressing files",
          "d) Scanning for malware"]),
    ],
    "Social Engineering": [
        ("What is phishing?",
         "c",
         ["a) A type of firewall",
          "b) A network scanning tool",
          "c) Deceptive attempts to steal sensitive info by impersonating trusted sources",
          "d) A method of encrypting emails"]),
        ("What is 'pretexting' in social engineering?",
         "a",
         ["a) Creating a fabricated scenario to manipulate someone into giving information",
          "b) Sending spam emails",
          "c) Installing malware remotely",
          "d) Brute-forcing a password"]),
        ("What does 'tailgating' mean in physical security?",
         "b",
         ["a) Following someone's internet traffic",
          "b) Physically following an authorized person into a restricted area",
          "c) Copying someone's keycard remotely",
          "d) Intercepting Wi-Fi signals"]),
        ("Which is the best defense against social engineering attacks?",
         "d",
         ["a) A stronger firewall",
          "b) Longer passwords",
          "c) More encryption",
          "d) Security awareness training for employees"]),
        ("What is 'vishing'?",
         "c",
         ["a) A type of malware",
          "b) Visual hacking by looking at someone's screen",
          "c) Voice phishing — using phone calls to deceive victims",
          "d) A vulnerability in VPNs"]),
        ("What is 'baiting' in social engineering?",
         "a",
         ["a) Leaving infected USB drives for victims to find and plug in",
          "b) Sending fake invoices",
          "c) Overloading a server with requests",
          "d) Cracking Wi-Fi passwords"]),
    ],
    "Malware & Intrusion": [
        ("What is a Trojan horse in cybersecurity?",
         "b",
         ["a) A type of firewall bypass",
          "b) Malware disguised as legitimate software",
          "c) A password cracking tool",
          "d) An encrypted virus"]),
        ("What does ransomware do?",
         "d",
         ["a) Steals your browser history",
          "b) Slows down your CPU",
          "c) Deletes all your files permanently",
          "d) Encrypts your files and demands payment for the key"]),
        ("What is a zero-day vulnerability?",
         "a",
         ["a) A flaw unknown to the vendor with no patch available",
          "b) A virus that activates at midnight",
          "c) A firewall with no rules set",
          "d) A system with no passwords"]),
        ("What is a rootkit?",
         "c",
         ["a) A tool for managing server roots",
          "b) An antivirus program",
          "c) Malware that hides itself deep in a system to maintain access",
          "d) A type of phishing email"]),
        ("What is a botnet?",
         "b",
         ["a) A secure network of servers",
          "b) A network of infected computers controlled remotely by an attacker",
          "c) A type of VPN",
          "d) A tool for scanning open ports"]),
        ("What does 'SQL injection' allow an attacker to do?",
         "d",
         ["a) Crash a web server",
          "b) Intercept Wi-Fi traffic",
          "c) Encrypt a database",
          "d) Manipulate or access a database through malicious input"]),
    ],
}